import clsx from 'clsx';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import HeaderContainer from '@/src/features/header/components/HeaderContainer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Venue App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx("bg-background min-h-screen", inter.className)}>
        <HeaderContainer />
        {children}
      </body>
    </html>
  )
}
